Repository miurahr/py7zr, pull requests merged in 2023-11, with the labels that each got.

#535 [Fix#534] IndexError / Worker initialization sets wrong last_file_index
  py7zr/py7zr.py
  tests/test_basic.py
Labels: bug

#541 chore: Support python 3.12
  .github/workflows/run-tox-tests.yml
  pyproject.toml
Labels: enhancement

#543 fix: Detect brotli import error
  docs/user_guide.rst
  py7zr/compressor.py
Labels: enhancement, documentation
