Repository miurahr/py7zr, pull requests merged in 2024-01, with the labels that each got.

#550 fix #540: replace deprecated functions on python 3.12
  tests/test_archive.py
  tests/test_extract.py
Labels: enhancement

#572 docs: update README.rst
  README.rst
Labels: documentation

#568 docs: make subsection of multivolume creation
  docs/user_guide.rst
Labels: documentation

#555 Speed up extraction when number of files is very large.
  py7zr/py7zr.py
Labels: enhancement, for extraction
